AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 with Flask app pulling code from S3

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key

# Requirement 2.1
#
# Requirement 2.2

Resources:

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::${S3BucketName}/*

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP + SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
      # Requirement 2.3

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName

      # Requirement 2.4
      ImageId: ""  # Ubuntu 22.04 (update for us-west-2 region)

      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref SecurityGroup

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y python3 python3-pip awscli

          # Requirement 2.5.1

          # Requirement 2.5.2

          # Requirement 2.5.3

          # Set environment variable
          # Requirement 2.5.4

          # Run app
          nohup python3 application.py > app.log 2>&1 &

Outputs:
  PublicIP:
    Description: Access the Flask app
    Value: !GetAtt EC2Instance.PublicIp
